// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: sS6ndo3eesH-
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: rza15Hvo13Ik/component
import TopSection from "../../TopSection"; // plasmic-import: kADghGVlNdQS/component
import Section from "../../Section"; // plasmic-import: u59lQpZjhY09/component
import PhotoGallery from "../../PhotoGallery"; // plasmic-import: gQd9sIYKcJ/component
import Section2 from "../../Section2"; // plasmic-import: 4rYfOxUY8n/component
import Section3 from "../../Section3"; // plasmic-import: K5KM4aUtvi/component
import Section4 from "../../Section4"; // plasmic-import: O0B8B9zzuX6/component
import Section5 from "../../Section5"; // plasmic-import: eiKdH07AQ2/component
import Section6 from "../../Section6"; // plasmic-import: fwF6B-mcVA/component
import Section8 from "../../Section8"; // plasmic-import: 9lYi5fZQnJ/component
import Footer from "../../Footer"; // plasmic-import: ZBwA144TOF/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: sS6ndo3eesH-/css
import shiningBlackpngSmgu9KCzu from "./images/shiningBlackpng.png"; // plasmic-import: SMGU9KCzu/picture

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box__iqTm8)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />

            <TopSection
              data-plasmic-name={"topSection"}
              data-plasmic-override={overrides.topSection}
              className={classNames("__wab_instance", sty.topSection)}
            />

            <Section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames("__wab_instance", sty.section)}
              subtitle={
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__imKV
                    )}
                  >
                    {
                      "Я приветствую Вас в моей клинике Константа Дентал. Кратко расскажу Вам о нас."
                    }
                  </div>

                  <img
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(defaultcss.img, sty.img)}
                    role={"img"}
                    src={shiningBlackpngSmgu9KCzu}
                  />
                </React.Fragment>
              }
              subtitleMain={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__o0Gml
                  )}
                >
                  {"Гуманенко Татьяна Владимировна"}
                </div>
              }
              title={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__mNEw0
                  )}
                >
                  {"Меня зовут"}
                </div>
              }
            />

            <PhotoGallery
              data-plasmic-name={"photoGallery"}
              data-plasmic-override={overrides.photoGallery}
              className={classNames("__wab_instance", sty.photoGallery)}
            />

            <Section2
              data-plasmic-name={"section2"}
              data-plasmic-override={overrides.section2}
              className={classNames("__wab_instance", sty.section2)}
            />

            <Section3
              className={classNames("__wab_instance", sty.section3__mKcw9)}
            />

            <Section3
              className={classNames("__wab_instance", sty.section3__lO19R)}
              mainTitle={"CEREC"}
              reverseView={"reverseView"}
              subTitle={
                "Новейший аппарат для быстрого и качественного восстановления и реставрации зубов, который используют в лучших клиниках по всему миру"
              }
            />

            <Section3
              className={classNames("__wab_instance", sty.section3__dbzp2)}
              mainTitle={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___6ROsd
                  )}
                >
                  {"Многофункциональные\nи новые стоматологические\nустановки"}
                </div>
              }
              simpleView={"simpleView"}
              subTitle={
                "Многофункциональные и новые стоматологические установки"
              }
            />

            <Section4
              data-plasmic-name={"section4"}
              data-plasmic-override={overrides.section4}
              className={classNames("__wab_instance", sty.section4)}
            />

            <Section5
              data-plasmic-name={"section5"}
              data-plasmic-override={overrides.section5}
              className={classNames("__wab_instance", sty.section5)}
            />

            <Section6
              data-plasmic-name={"section6"}
              data-plasmic-override={overrides.section6}
              className={classNames("__wab_instance", sty.section6)}
            />

            <Section8
              data-plasmic-name={"section8"}
              data-plasmic-override={overrides.section8}
              className={classNames("__wab_instance", sty.section8)}
            />

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "topSection",
    "section",
    "img",
    "photoGallery",
    "section2",
    "section4",
    "section5",
    "section6",
    "section8",
    "footer"
  ],

  header: ["header"],
  topSection: ["topSection"],
  section: ["section", "img"],
  img: ["img"],
  photoGallery: ["photoGallery"],
  section2: ["section2"],
  section4: ["section4"],
  section5: ["section5"],
  section6: ["section6"],
  section8: ["section8"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    topSection: makeNodeComponent("topSection"),
    section: makeNodeComponent("section"),
    img: makeNodeComponent("img"),
    photoGallery: makeNodeComponent("photoGallery"),
    section2: makeNodeComponent("section2"),
    section4: makeNodeComponent("section4"),
    section5: makeNodeComponent("section5"),
    section6: makeNodeComponent("section6"),
    section8: makeNodeComponent("section8"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
