// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: i6uwCB2O_K
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicYandexMaps.module.css"; // plasmic-import: i6uwCB2O_K/css

export const PlasmicYandexMaps__VariantProps = new Array();

export const PlasmicYandexMaps__ArgProps = new Array();

function PlasmicYandexMaps__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        <iframe
            src="https://yandex.ru/map-widget/v1/?um=constructor%3Ae460a12e15a8ff18e10d14c14231fe68c7ec77a980910394c65217cd144167b8&amp;source=constructor"
            width="100%" height="450" frameBorder="0"/>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicYandexMaps__ArgProps,
      internalVariantPropNames: PlasmicYandexMaps__VariantProps
    });

    return PlasmicYandexMaps__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicYandexMaps";
  } else {
    func.displayName = `PlasmicYandexMaps.${nodeName}`;
  }
  return func;
}

export const PlasmicYandexMaps = Object.assign(
  // Top-level PlasmicYandexMaps renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicYandexMaps
    internalVariantProps: PlasmicYandexMaps__VariantProps,
    internalArgProps: PlasmicYandexMaps__ArgProps
  }
);

export default PlasmicYandexMaps;
/* prettier-ignore-end */
