// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: ZBwA144TOF
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicFooter.module.css"; // plasmic-import: ZBwA144TOF/css
import telegramWhitepngAtTkDiSdj from "./images/telegramWhitepng.png"; // plasmic-import: ATTkDISdj/picture
import whatsappWhitepngW5D1LrhNi from "./images/whatsappWhitepng.png"; // plasmic-import: W5D1lrhNI/picture
import facebookWhitepngQMsAYx5J2 from "./images/facebookWhitepng.png"; // plasmic-import: QMsAYx5J2/picture
import instagramWhitepngKAIt4ZfNr from "./images/instagramWhitepng.png"; // plasmic-import: kAIt4ZfNr/picture
import konstantaDental2PngGgyFcHxwH from "./images/konstantaDental2Png.png"; // plasmic-import: GgyFCHxwH/picture

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__xBo2)}>
        <div className={classNames(defaultcss.all, sty.box___9BkyX)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box___6X9Ti)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bk89
              )}
            >
              {"+(900) 000 00-00"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box___4OaB9)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__txbOh)}
                role={"img"}
                src={telegramWhitepngAtTkDiSdj}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__jyKo)}
                role={"img"}
                src={whatsappWhitepngW5D1LrhNi}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___13KJw)}
                role={"img"}
                src={facebookWhitepngQMsAYx5J2}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___3IXxn)}
                role={"img"}
                src={instagramWhitepngKAIt4ZfNr}
              />
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__iHMt
              )}
            >
              {"konstantadental@gmail.com"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qx2Fu
              )}
            >
              {"г. Москва, г. Троицк, Октябрьский проспект 23-А"}
            </div>
          </p.Stack>
        </div>

        <div className={classNames(defaultcss.all, sty.box___6Dwjk)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__hppMp
            )}
          >
            {"Главная"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__lt9Ui
            )}
          >
            {"Услуги и цены"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__nld7P
            )}
          >
            {"Специалисты"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__bDKh
            )}
          >
            {"F.A.Q."}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__ce08T
            )}
          >
            {"Контакты"}
          </div>
        </div>

        <div className={classNames(defaultcss.all, sty.box__wxIzc)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__nSoR9
            )}
          >
            {"Пользовательское соглашение"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__crBTt
            )}
          >
            {"Общая информация"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__cYxk
            )}
          >
            {"ИНН 7751138982"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__aicka
            )}
          >
            {"ОГРН 1187746103126"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__jqx8D
            )}
          >
            {"от 1 февраля 2018 г."}
          </div>
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.box__lFFn)}>
        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img__ai3NB)}
          role={"img"}
          src={konstantaDental2PngGgyFcHxwH}
        />

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__yRw6J
          )}
        >
          {"Константа Дентал © 2020 Все права защищены"}
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
