// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: O0B8B9zzuX6
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import JobsItem from "../../JobsItem"; // plasmic-import: 7NqkOLAQg9/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicSection4.module.css"; // plasmic-import: O0B8B9zzuX6/css
import ToothWhiteningBlacksvgIcon from "./icons/PlasmicIcon__ToothWhiteningBlacksvg"; // plasmic-import: khWLi80jHa/icon
import AesteticsvgIcon from "./icons/PlasmicIcon__Aesteticsvg"; // plasmic-import: GCsBs8QiTB/icon
import Aestetic2Svg2Icon from "./icons/PlasmicIcon__Aestetic2Svg2"; // plasmic-import: _uvtO_GFXt/icon
import ChildsvgIcon from "./icons/PlasmicIcon__Childsvg"; // plasmic-import: b_0lp8T_9/icon
import Child2SvgIcon from "./icons/PlasmicIcon__Child2Svg"; // plasmic-import: K_b5e0JY1L/icon
import ImplantsvgIcon from "./icons/PlasmicIcon__Implantsvg"; // plasmic-import: XCxVFtLk-K/icon
import Implant2SvgIcon from "./icons/PlasmicIcon__Implant2Svg"; // plasmic-import: gyYZ3zgYYg/icon
import CleansvgIcon from "./icons/PlasmicIcon__Cleansvg"; // plasmic-import: 8TsnJpby6/icon
import Clean2SvgIcon from "./icons/PlasmicIcon__Clean2Svg"; // plasmic-import: bzJiXADxFO/icon
import OrtodontsvgIcon from "./icons/PlasmicIcon__Ortodontsvg"; // plasmic-import: ABviE8cU4J/icon
import Ortodont2SvgIcon from "./icons/PlasmicIcon__Ortodont2Svg"; // plasmic-import: 6UKqezNH6J/icon
import ProtezirovaniesvgIcon from "./icons/PlasmicIcon__Protezirovaniesvg"; // plasmic-import: 4kqX1tT-Nw/icon
import Protezirovanie2SvgIcon from "./icons/PlasmicIcon__Protezirovanie2Svg"; // plasmic-import: 6Bvpon50IM/icon
import ToothMoneysvg2Icon from "./icons/PlasmicIcon__ToothMoneysvg2"; // plasmic-import: GA4jYd1Tst/icon

export const PlasmicSection4__VariantProps = new Array();

export const PlasmicSection4__ArgProps = new Array();

function PlasmicSection4__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__b6TIp)}>
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__e0FUx)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__a1Y3J
            )}
          >
            {"Наши услуги"}
          </div>

          <ToothWhiteningBlacksvgIcon
            className={classNames(defaultcss.all, sty.svg__k0C80)}
            role={"img"}
          />
        </p.Stack>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__cbrMv
          )}
        >
          {
            "В нашей клинике мы используем высокотехнологичное оборудование, которое позволяет нам добиваться максимальной четкости при диагностический аппарат, благодаря которому наши врачи безболезненно проводят день."
          }
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box___9ZA3E)}
      >
        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__fC6UL)}
          jobsItemImg={
            <AesteticsvgIcon
              className={classNames(defaultcss.all, sty.svg__anMDq)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Aestetic2Svg2Icon
              className={classNames(defaultcss.all, sty.svg__uxptY)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qeTjW
              )}
            >
              {"Лечение зубов"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xFkc
              )}
            >
              {"лечение кариеса, каналов"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__rsOni)}
          jobsItemImg={
            <ChildsvgIcon
              className={classNames(defaultcss.all, sty.svg__vseg3)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Child2SvgIcon
              className={classNames(defaultcss.all, sty.svg__qSz61)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__jqlB
              )}
            >
              {"Детская стоматология"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__mAAa
              )}
            >
              {"лечение, удаление, профилактика, гермитазация фиссур"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__ymgx2)}
          jobsItemImg={
            <ImplantsvgIcon
              className={classNames(defaultcss.all, sty.svg__mXbxv)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Implant2SvgIcon
              className={classNames(defaultcss.all, sty.svg__gSxjD)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__lV892
              )}
            >
              {"Хирургия"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__mDu3J
              )}
            >
              {"Удаление, имплантология"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem___1L0F)}
          jobsItemImg={
            <CleansvgIcon
              className={classNames(defaultcss.all, sty.svg__rCwg)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Clean2SvgIcon
              className={classNames(defaultcss.all, sty.svg___5JlOd)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__f0ZMo
              )}
            >
              {"Эстетика и уход"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__g5UUp
              )}
            >
              {
                "профес.чистка, реминерализация, виниры, отбеливание, реставрация"
              }
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem___6AkGo)}
          jobsItemImg={
            <OrtodontsvgIcon
              className={classNames(defaultcss.all, sty.svg__g4OTe)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Ortodont2SvgIcon
              className={classNames(defaultcss.all, sty.svg__r4S5Y)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__t0VjC
              )}
            >
              {"Ортодонтия"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__on1C
              )}
            >
              {"Исправление прикуса, выравнивание зубов"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__q5QPa)}
          jobsItemImg={
            <ProtezirovaniesvgIcon
              className={classNames(defaultcss.all, sty.svg__tVmQh)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Protezirovanie2SvgIcon
              className={classNames(defaultcss.all, sty.svg__vcGms)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__y9T3Y
              )}
            >
              {"Протезирование"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__jPgn2
              )}
            >
              {"коронки, протезы"}
            </div>
          }
        />
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__i0IXi)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__x3Jd
          )}
        >
          {"С полным перечнем услуг и ценами Вы можете ознакомится здесь"}
        </div>

        <button
          data-plasmic-name={"prices"}
          data-plasmic-override={overrides.prices}
          className={classNames(defaultcss.button, sty.prices)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___5PsXh
            )}
          >
            {"Услуги и цены"}
          </div>
        </button>

        <ToothMoneysvg2Icon
          className={classNames(defaultcss.all, sty.svg__qmktb)}
          role={"img"}
        />
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "prices"],
  prices: ["prices"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSection4__ArgProps,
      internalVariantPropNames: PlasmicSection4__VariantProps
    });

    return PlasmicSection4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSection4";
  } else {
    func.displayName = `PlasmicSection4.${nodeName}`;
  }
  return func;
}

export const PlasmicSection4 = Object.assign(
  // Top-level PlasmicSection4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    prices: makeNodeComponent("prices"),
    // Metadata about props expected for PlasmicSection4
    internalVariantProps: PlasmicSection4__VariantProps,
    internalArgProps: PlasmicSection4__ArgProps
  }
);

export default PlasmicSection4;
/* prettier-ignore-end */
