// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: aSjR2lLD1O
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicSlider1.module.css"; // plasmic-import: aSjR2lLD1O/css
import gallery2Png95BbWlH5R from "./images/gallery2Png.png"; // plasmic-import: 95BbWlH5r/picture
import gallery1JpgOqoMvxIli from "./images/gallery1Jpg.jpeg"; // plasmic-import: oqoMvxILI/picture
import gallery3JpgLMui1Dmmy from "./images/gallery3Jpg.jpeg"; // plasmic-import: lMUI1dmmy/picture

export const PlasmicSlider1__VariantProps = new Array();

export const PlasmicSlider1__ArgProps = new Array(
  "photo1",
  "photo2",
  "photo3",
  "photo4"
);

function PlasmicSlider1__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        <p.PlasmicSlot
          defaultContents={
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img___2Pn1D)}
              role={"img"}
              src={gallery2Png95BbWlH5R}
            />
          }
          value={args.photo1}
        />

        <p.PlasmicSlot
          defaultContents={
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__pkG3)}
              role={"img"}
              src={gallery1JpgOqoMvxIli}
            />
          }
          value={args.photo2}
        />

        <p.PlasmicSlot
          defaultContents={
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__zrd9E)}
              role={"img"}
              src={gallery3JpgLMui1Dmmy}
            />
          }
          value={args.photo3}
        />

        <p.PlasmicSlot
          defaultContents={
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__iVovs)}
              role={"img"}
              src={gallery2Png95BbWlH5R}
            />
          }
          value={args.photo4}
        />
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSlider1__ArgProps,
      internalVariantPropNames: PlasmicSlider1__VariantProps
    });

    return PlasmicSlider1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSlider1";
  } else {
    func.displayName = `PlasmicSlider1.${nodeName}`;
  }
  return func;
}

export const PlasmicSlider1 = Object.assign(
  // Top-level PlasmicSlider1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicSlider1
    internalVariantProps: PlasmicSlider1__VariantProps,
    internalArgProps: PlasmicSlider1__ArgProps
  }
);

export default PlasmicSlider1;
/* prettier-ignore-end */
