// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: kvSBRIpxnNs6
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicFeatureCard.module.css"; // plasmic-import: kvSBRIpxnNs6/css

export const PlasmicFeatureCard__VariantProps = new Array("_long");

export const PlasmicFeatureCard__ArgProps = new Array(
  "iconFront",
  "title",
  "description",
  "iconBack"
);

function PlasmicFeatureCard__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root___long]: hasVariant(variants, "_long", "_long")
      })}
    >
      {(hasVariant(variants, "_long", "_long") ? false : true) ? (
        <div
          className={classNames(defaultcss.all, sty.box___7Th3U, {
            [sty.box___long___7Th3UhLw0]: hasVariant(variants, "_long", "_long")
          })}
        >
          <div
            className={classNames(defaultcss.all, sty.box__dWjqo, {
              [sty.box___long__dWjqOhLw0]: hasVariant(
                variants,
                "_long",
                "_long"
              )
            })}
          >
            <p.PlasmicSlot
              defaultContents={
                <svg
                  className={classNames(defaultcss.all, sty.svg__aV2SI)}
                  role={"img"}
                />
              }
              value={args.iconFront}
            />
          </div>
        </div>
      ) : null}

      <div
        className={classNames(defaultcss.all, sty.box__msq4H, {
          [sty.box___long__msq4HhLw0]: hasVariant(variants, "_long", "_long")
        })}
      >
        <p.PlasmicSlot
          defaultContents={"Title"}
          value={args.title}
          className={classNames(sty.slotTitle, {
            [sty.slotTitle___long]: hasVariant(variants, "_long", "_long")
          })}
        />

        <p.PlasmicSlot
          defaultContents={
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
          }
          value={args.description}
          className={classNames(sty.slotDescription, {
            [sty.slotDescription___long]: hasVariant(variants, "_long", "_long")
          })}
        />
      </div>

      {(hasVariant(variants, "_long", "_long") ? true : false) ? (
        <div
          className={classNames(defaultcss.all, sty.box__d2Ht, {
            [sty.box___long__d2HthLw0]: hasVariant(variants, "_long", "_long")
          })}
        >
          <p.PlasmicSlot
            defaultContents={
              <svg
                className={classNames(defaultcss.all, sty.svg__gk0Hw)}
                role={"img"}
              />
            }
            value={args.iconBack}
          />
        </div>
      ) : null}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeatureCard__ArgProps,
      internalVariantPropNames: PlasmicFeatureCard__VariantProps
    });

    return PlasmicFeatureCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeatureCard";
  } else {
    func.displayName = `PlasmicFeatureCard.${nodeName}`;
  }
  return func;
}

export const PlasmicFeatureCard = Object.assign(
  // Top-level PlasmicFeatureCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFeatureCard
    internalVariantProps: PlasmicFeatureCard__VariantProps,
    internalArgProps: PlasmicFeatureCard__ArgProps
  }
);

export default PlasmicFeatureCard;
/* prettier-ignore-end */
