// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bGhfLbpuPrsnLdpUo1t3d
// Component: jxI2rvkZX6
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import LinkButton from "../../LinkButton"; // plasmic-import: Dumym2P0mPVt/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: j0pD0TqEwUAIP/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light.module.css"; // plasmic-import: bGhfLbpuPrsnLdpUo1t3d/projectcss
import * as sty from "./PlasmicMenuItems.module.css"; // plasmic-import: jxI2rvkZX6/css

export const PlasmicMenuItems__VariantProps = new Array();

export const PlasmicMenuItems__ArgProps = new Array();

function PlasmicMenuItems__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box___5YxbR)}>
        <LinkButton
          className={classNames("__wab_instance", sty.linkButton__xRix)}
          href={"/features"}
          text={"Главная"}
          type={"small"}
        />

        <LinkButton
          className={classNames("__wab_instance", sty.linkButton__pK4)}
          href={"/pricing"}
          text={"Услуги и цены"}
          type={"small"}
        />

        <LinkButton
          className={classNames("__wab_instance", sty.linkButton___8UBgi)}
          text={"Специалисты"}
          type={"small"}
        />

        <LinkButton
          className={classNames("__wab_instance", sty.linkButton__unsw)}
          text={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__x5HcH
              )}
            >
              {"F.A.Q."}
            </div>
          }
          type={"small"}
        />

        <LinkButton
          className={classNames("__wab_instance", sty.linkButton__fDtQt)}
          text={"Контакты"}
          type={"small"}
        />
      </div>

      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__dpuPv
        )}
      >
        {"+7(900)000 00-00"}
      </div>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenuItems__ArgProps,
      internalVariantPropNames: PlasmicMenuItems__VariantProps
    });

    return PlasmicMenuItems__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuItems";
  } else {
    func.displayName = `PlasmicMenuItems.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuItems = Object.assign(
  // Top-level PlasmicMenuItems renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMenuItems
    internalVariantProps: PlasmicMenuItems__VariantProps,
    internalArgProps: PlasmicMenuItems__ArgProps
  }
);

export default PlasmicMenuItems;
/* prettier-ignore-end */
