// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicYandexMaps } from "./plasmic/copy_of_simple_light/PlasmicYandexMaps";

function YandexMaps(props) {
  return (
      <div className={props.className}>
        <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Ae460a12e15a8ff18e10d14c14231fe68c7ec77a980910394c65217cd144167b8&amp;source=constructor" width="100%" height="450" frameBorder="0"/>
      </div>
  );
}

export default YandexMaps;
