// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rRiHBMbiCNZ6Mp9qsJpkyN
// Component: mwKnfShdBNNjS
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_simple_light.module.css"; // plasmic-import: rRiHBMbiCNZ6Mp9qsJpkyN/projectcss
import * as sty from "./PlasmicFooter.module.css"; // plasmic-import: mwKnfShdBNNjS/css
import telegramWhitepng2H7VPsaGa8OOy from "./images/telegramWhitepng.png"; // plasmic-import: 2H7vPsaGA8oOy/picture
import whatsappWhitepngMNkkYbPv3OcAj from "./images/whatsappWhitepng.png"; // plasmic-import: MNkkYBPv3OCAj/picture
import facebookWhitepngB5KqrmaFf8D from "./images/facebookWhitepng.png"; // plasmic-import: b5KQRMAFf-8-D/picture
import instagramWhitepngDk3DyPpJSzhIp from "./images/instagramWhitepng.png"; // plasmic-import: Dk3dyPpJSzhIp/picture
import konstantaDental2PngZA7JmbMxjRaDe from "./images/konstantaDental2Png.png"; // plasmic-import: zA7JmbMXJRaDE/picture

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box___1UyZr)}>
        <div className={classNames(defaultcss.all, sty.box___70OG8)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__ht887)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__myACc
              )}
            >
              {"+(900) 000 00-00"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__yBnel)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__coFQf)}
                role={"img"}
                src={telegramWhitepng2H7VPsaGa8OOy}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__txa8I)}
                role={"img"}
                src={whatsappWhitepngMNkkYbPv3OcAj}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__bcJwO)}
                role={"img"}
                src={facebookWhitepngB5KqrmaFf8D}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__cCrhb)}
                role={"img"}
                src={instagramWhitepngDk3DyPpJSzhIp}
              />
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__aIvz6
              )}
            >
              {"konstantadental@gmail.com"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bgAde
              )}
            >
              {"г. Москва, г. Троицк, Октябрьский проспект 23-А"}
            </div>
          </p.Stack>
        </div>

        <div className={classNames(defaultcss.all, sty.box___9Hvce)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___2KbUt
            )}
          >
            {"Главная"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__yhZDw
            )}
          >
            {"Услуги и цены"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__q5F0Y
            )}
          >
            {"Специалисты"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___99PW
            )}
          >
            {"F.A.Q."}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__mi0Pt
            )}
          >
            {"Контакты"}
          </div>
        </div>

        <div className={classNames(defaultcss.all, sty.box__ud0QM)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__nVp1E
            )}
          >
            {"Пользовательское соглашение"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__ak6Ja
            )}
          >
            {"Общая информация"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__z10Ax
            )}
          >
            {"ИНН 7751138982"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___45Y6H
            )}
          >
            {"ОГРН 1187746103126"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__w0LU
            )}
          >
            {"от 1 февраля 2018 г."}
          </div>
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.box__jd1Md)}>
        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img__sJiW)}
          role={"img"}
          src={konstantaDental2PngZA7JmbMxjRaDe}
        />

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__moPlv
          )}
        >
          {"Константа Дентал © 2020 Все права защищены"}
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
