// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rRiHBMbiCNZ6Mp9qsJpkyN
// Component: mMDkq_hl5tD3_
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import JobsItem from "../../JobsItem"; // plasmic-import: CDyDuvLezUsVf/component
import PinkButton from "../../PinkButton"; // plasmic-import: 0e89kY6kMy/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_simple_light.module.css"; // plasmic-import: rRiHBMbiCNZ6Mp9qsJpkyN/projectcss
import * as sty from "./PlasmicSection4.module.css"; // plasmic-import: mMDkq_hl5tD3_/css
import ToothWhiteningBlacksvgIcon from "./icons/PlasmicIcon__ToothWhiteningBlacksvg"; // plasmic-import: PXMpwjhztkarF/icon
import AesteticsvgIcon from "./icons/PlasmicIcon__Aesteticsvg"; // plasmic-import: _-EX7DSMxZ8Jd/icon
import Aestetic2Svg2Icon from "./icons/PlasmicIcon__Aestetic2Svg2"; // plasmic-import: aMbN3iWX8jLzY/icon
import ChildsvgIcon from "./icons/PlasmicIcon__Childsvg"; // plasmic-import: MuTps5uvEhCO6/icon
import Child2SvgIcon from "./icons/PlasmicIcon__Child2Svg"; // plasmic-import: S3ueUpzylJptA/icon
import ImplantsvgIcon from "./icons/PlasmicIcon__Implantsvg"; // plasmic-import: 4y5gkZKUGiw8Z/icon
import Implant2SvgIcon from "./icons/PlasmicIcon__Implant2Svg"; // plasmic-import: CmDllxaRb-XlC/icon
import CleansvgIcon from "./icons/PlasmicIcon__Cleansvg"; // plasmic-import: j0J9n5eB0Nm5S/icon
import Clean2SvgIcon from "./icons/PlasmicIcon__Clean2Svg"; // plasmic-import: 08X-sXpqj4Di7/icon
import OrtodontsvgIcon from "./icons/PlasmicIcon__Ortodontsvg"; // plasmic-import: zOFCsQqnoLxBq/icon
import Ortodont2SvgIcon from "./icons/PlasmicIcon__Ortodont2Svg"; // plasmic-import: 3dfuGCBtahO6x/icon
import ProtezirovaniesvgIcon from "./icons/PlasmicIcon__Protezirovaniesvg"; // plasmic-import: a_sqaX_0MTSx6/icon
import Protezirovanie2SvgIcon from "./icons/PlasmicIcon__Protezirovanie2Svg"; // plasmic-import: pLw60QPb3wDQ1/icon
import ToothMoneysvg2Icon from "./icons/PlasmicIcon__ToothMoneysvg2"; // plasmic-import: ZcBCuuOpliGWl/icon

export const PlasmicSection4__VariantProps = new Array();

export const PlasmicSection4__ArgProps = new Array();

function PlasmicSection4__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__omqTh)}>
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__mop7K)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__cCwXl
            )}
          >
            {"Наши услуги"}
          </div>

          <ToothWhiteningBlacksvgIcon
            className={classNames(defaultcss.all, sty.svg__dahpr)}
            role={"img"}
          />
        </p.Stack>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__qub3B
          )}
        >
          {
            "В нашей клинике мы используем высокотехнологичное оборудование, которое позволяет нам добиваться максимальной четкости при диагностический аппарат, благодаря которому наши врачи безболезненно проводят день."
          }
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__rx6LV)}
      >
        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem___2EXvz)}
          jobsItemImg={
            <AesteticsvgIcon
              className={classNames(defaultcss.all, sty.svg__o1Tt)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Aestetic2Svg2Icon
              className={classNames(defaultcss.all, sty.svg__nYPn)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wDgjW
              )}
            >
              {"Лечение зубов"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bJbqv
              )}
            >
              {"лечение кариеса, каналов"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__pbi1K)}
          jobsItemImg={
            <ChildsvgIcon
              className={classNames(defaultcss.all, sty.svg__mjqQo)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Child2SvgIcon
              className={classNames(defaultcss.all, sty.svg__fhb1W)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__zop5J
              )}
            >
              {"Детская стоматология"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__u3Swn
              )}
            >
              {"лечение, удаление, профилактика, гермитазация фиссур"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem___7QJci)}
          jobsItemImg={
            <ImplantsvgIcon
              className={classNames(defaultcss.all, sty.svg__lXkj6)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Implant2SvgIcon
              className={classNames(defaultcss.all, sty.svg___3KoYq)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__kJu3K
              )}
            >
              {"Хирургия"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__tCyBa
              )}
            >
              {"Удаление, имплантология"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__kLjHp)}
          jobsItemImg={
            <CleansvgIcon
              className={classNames(defaultcss.all, sty.svg__lSemv)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Clean2SvgIcon
              className={classNames(defaultcss.all, sty.svg__smyfb)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__zHlcF
              )}
            >
              {"Эстетика и уход"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wAHgZ
              )}
            >
              {
                "профес.чистка, реминерализация, виниры, отбеливание, реставрация"
              }
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem___0JbJ)}
          jobsItemImg={
            <OrtodontsvgIcon
              className={classNames(defaultcss.all, sty.svg__jVms3)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Ortodont2SvgIcon
              className={classNames(defaultcss.all, sty.svg__qNm9R)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__elG8
              )}
            >
              {"Ортодонтия"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__dwvI
              )}
            >
              {"Исправление прикуса, выравнивание зубов"}
            </div>
          }
        />

        <JobsItem
          className={classNames("__wab_instance", sty.jobsItem__aGwjb)}
          jobsItemImg={
            <ProtezirovaniesvgIcon
              className={classNames(defaultcss.all, sty.svg__xoMlx)}
              role={"img"}
            />
          }
          jobsItemImg2={
            <Protezirovanie2SvgIcon
              className={classNames(defaultcss.all, sty.svg__aP3Qc)}
              role={"img"}
            />
          }
          mainTitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__yA5B
              )}
            >
              {"Протезирование"}
            </div>
          }
          subtitle={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__vYvRi
              )}
            >
              {"коронки, протезы"}
            </div>
          }
        />
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__i8Sht)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box___9Sjwi
          )}
        >
          {"С полным перечнем услуг и ценами Вы можете ознакомится здесь"}
        </div>

        <PinkButton
          data-plasmic-name={"pinkButton"}
          data-plasmic-override={overrides.pinkButton}
          className={classNames("__wab_instance", sty.pinkButton)}
        />

        <ToothMoneysvg2Icon
          className={classNames(defaultcss.all, sty.svg__pvgFn)}
          role={"img"}
        />
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "pinkButton"],
  pinkButton: ["pinkButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSection4__ArgProps,
      internalVariantPropNames: PlasmicSection4__VariantProps
    });

    return PlasmicSection4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSection4";
  } else {
    func.displayName = `PlasmicSection4.${nodeName}`;
  }
  return func;
}

export const PlasmicSection4 = Object.assign(
  // Top-level PlasmicSection4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pinkButton: makeNodeComponent("pinkButton"),
    // Metadata about props expected for PlasmicSection4
    internalVariantProps: PlasmicSection4__VariantProps,
    internalArgProps: PlasmicSection4__ArgProps
  }
);

export default PlasmicSection4;
/* prettier-ignore-end */
