// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rRiHBMbiCNZ6Mp9qsJpkyN
// Component: cr8qTWYzmiKt
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  useTrigger,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_simple_light.module.css"; // plasmic-import: rRiHBMbiCNZ6Mp9qsJpkyN/projectcss
import * as sty from "./PlasmicSection.module.css"; // plasmic-import: cr8qTWYzmiKt/css
import PlaceholdersvgIcon from "./icons/PlasmicIcon__Placeholdersvg"; // plasmic-import: efbLTS6Zlx6ef/icon
import doctorWritingpngLPqVlg3TLjeZk from "./images/doctorWritingpng.png"; // plasmic-import: lPQVlg3TLjeZk/picture
import tooth4Greysvg2PJXvWkEr4Ml from "./images/tooth4Greysvg.svg"; // plasmic-import: 2pJXvWkEr4_ML/picture

export const PlasmicSection__VariantProps = new Array();

export const PlasmicSection__ArgProps = new Array(
  "title",
  "subtitleMain",
  "subtitle"
);

function PlasmicSection__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div className={classNames(defaultcss.all, sty.box__m5GWm)}>
        <p.PlasmicSlot
          defaultContents={
            "Trusted by over 20,000 companies all over the world"
          }
          value={args.title}
          className={classNames(sty.slotTitle)}
        />

        <p.PlasmicSlot
          defaultContents={"Enter some text"}
          value={args.subtitleMain}
        />

        <p.PlasmicSlot
          defaultContents={"Enter some text"}
          value={args.subtitle}
        />
      </div>

      <div className={classNames(defaultcss.all, sty.box__tat6M)}>
        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img__iJk8)}
          role={"img"}
          src={doctorWritingpngLPqVlg3TLjeZk}
        />

        <ul
          data-plasmic-name={"ul"}
          data-plasmic-override={overrides.ul}
          className={classNames(defaultcss.ul, sty.ul)}
        >
          <li className={classNames(defaultcss.li, sty.li___1KZmm)}>
            <div className={classNames(defaultcss.all, sty.box__tUHzZ)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__c5Mdd
                )}
              >
                {"Мы - стоматологическая клиника"}
              </div>

              <a
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.link
                )}
                href={"#contacts"}
              >
                {triggers.hover_root ? " в Троицке" : " в Троицке"}
              </a>
            </div>

            <PlaceholdersvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(defaultcss.all, sty.svg)}
              role={"img"}
            />
          </li>

          <li
            className={classNames(
              defaultcss.li,
              defaultcss.__wab_text,
              sty.li___1WgB
            )}
          >
            {"Современное уникальное оборудование"}
          </li>

          <li
            className={classNames(
              defaultcss.li,
              defaultcss.__wab_text,
              sty.li__uXr4K
            )}
          >
            {"3 кабинета"}
          </li>

          <li
            className={classNames(
              defaultcss.li,
              defaultcss.__wab_text,
              sty.li__bv6Gk
            )}
          >
            {"Работаем с 2004 года"}
          </li>
        </ul>
      </div>

      <img
        alt={""}
        className={classNames(defaultcss.img, sty.img__rb2DM)}
        role={"img"}
        src={tooth4Greysvg2PJXvWkEr4Ml}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "ul", "link", "svg"],
  ul: ["ul", "link", "svg"],
  link: ["link"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSection__ArgProps,
      internalVariantPropNames: PlasmicSection__VariantProps
    });

    return PlasmicSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSection";
  } else {
    func.displayName = `PlasmicSection.${nodeName}`;
  }
  return func;
}

export const PlasmicSection = Object.assign(
  // Top-level PlasmicSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    ul: makeNodeComponent("ul"),
    link: makeNodeComponent("link"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicSection
    internalVariantProps: PlasmicSection__VariantProps,
    internalArgProps: PlasmicSection__ArgProps
  }
);

export default PlasmicSection;
/* prettier-ignore-end */
