// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { Swiper, SwiperSlide} from 'swiper/react';
import 'swiper/swiper.scss';
import './style.sass';
import swiper, { Autoplay } from 'swiper';
import {useCallback, useState} from "react";
import ImageViewer from "react-simple-image-viewer";
import slideImage1 from '../images/photogallerySlides/DSC_0001_S.jpg';
import slideImage2 from '../images/photogallerySlides/DSC_0004_S.jpg';
import slideImage3 from '../images/photogallerySlides/DSC_0022_S.jpg';
import slideImage4 from '../images/photogallerySlides/DSC_0050_S.jpg';
import slideImage5 from '../images/photogallerySlides/DSC_0052_S.jpg';
import slideImage7 from '../images/photogallerySlides/DSC_0055_S.jpg';
import slideImage8 from '../images/photogallerySlides/DSC_0055_S.jpg';
import slideImage9 from '../images/photogallerySlides/DSC_0055_S.jpg';
import slideImage10 from '../images/photogallerySlides/DSC_0065_S.jpg';
import slideImage11 from '../images/photogallerySlides/DSC_0079_S.jpg';
import slideImage12 from '../images/photogallerySlides/DSC_0143_S.jpg';
import slideImage13 from '../images/photogallerySlides/DSC_0159_S.jpg';
import slideImage14 from '../images/photogallerySlides/DSC_0182_S.jpg';
import slideImage15 from '../images/photogallerySlides/DSC_0186_S.jpg';
import slideImage16 from '../images/photogallerySlides/DSC_0198_S.jpg';
import slideImage17 from '../images/photogallerySlides/DSC_0211_S.jpg';

const Slider1 = (props) => {
    const [currentImage, setCurrentImage] = useState(0);
    const [isViewerOpen, setIsViewerOpen] = useState(false);

    const images = [
        slideImage1,
        slideImage2,
        slideImage3,
        slideImage4,
        slideImage5,
        slideImage7,
        slideImage8,
        slideImage9,
        slideImage10,
        slideImage11,
        slideImage12,
        slideImage13,
        slideImage14,
        slideImage15,
        slideImage16,
        slideImage17,
    ];

    const openImageViewer = useCallback(index => {
        switchSlidersVisibility.show();
        setCurrentImage(index);
        setIsViewerOpen(true);
    }, []);

    const closeImageViewer = () => {
        setCurrentImage(0);
        setIsViewerOpen(false);
        switchSlidersVisibility.hide();
    };

    const switchSlidersVisibility = {
        show: ()=>{
            let sliderElements = document.getElementsByClassName('swiper-wrapper');
            Array.prototype.forEach.call(sliderElements, function(sliderElement){
                sliderElement.classList.add('visibility-hidden');
            });
        },
        hide: ()=>{
            let sliderElements = document.getElementsByClassName('swiper-wrapper');
            Array.prototype.forEach.call(sliderElements, function(sliderElement){
                sliderElement.classList.remove('visibility-hidden');
            });
        }
    }

    const swiperParams = {
        loopFillGroupWithBlank: true,
        autoplay: {
            delay: 3000,
            disableOnInteraction: false
        },
        spaceBetween: 20,
        slidesPerView: 'auto',
        loop: true
    };
    swiper.use([Autoplay]);
  return (

      <Swiper {...swiperParams}>
          {images.map((src, index) => (
              <SwiperSlide>
                  <img
                      src={src}
                      onClick={() => openImageViewer(index)}
                      key={index}
                      alt="Фотогалерея клиники"
                      className={'slider-image'}
                  />
              </SwiperSlide>
          ))}
          {isViewerOpen && (
              <ImageViewer
                  src={images}
                  currentIndex={currentImage}
                  onClose={closeImageViewer}
                  backgroundStyle={{
                      backgroundColor: "rgba(0,0,0,0.9)"
                  }}
              />
          )}
      </Swiper>
  );
  // return <PlasmicSlider1 {...props} />;
}

export default Slider1;
